spring:
  jpa:
    hibernate:
      # create\none
      ddl-auto: create  
      # useSSL: false
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?useSSL=false
    username: root
    password: 123456
server:
  port: 8080
  address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - beans
  endpoint:
    health:
      show-details: ALWAYS